"""changed column names

Revision ID: d562788bf607
Revises: d653e9815e5f
Create Date: 2020-12-18 10:43:58.116694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd562788bf607'
down_revision = 'd653e9815e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('pos', sa.String(), nullable=True),
    sa.Column('mpg', sa.Float(), nullable=True),
    sa.Column('fta', sa.Float(), nullable=True),
    sa.Column('ftp', sa.Float(), nullable=True),
    sa.Column('tpa', sa.Float(), nullable=True),
    sa.Column('tpp', sa.Float(), nullable=True),
    sa.Column('thpa', sa.Float(), nullable=True),
    sa.Column('thpp', sa.Float(), nullable=True),
    sa.Column('ppg', sa.Float(), nullable=True),
    sa.Column('rpg', sa.Float(), nullable=True),
    sa.Column('apg', sa.Float(), nullable=True),
    sa.Column('spg', sa.Float(), nullable=True),
    sa.Column('bpg', sa.Float(), nullable=True),
    sa.Column('topg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player')
    # ### end Alembic commands ###
