"""added columns to Player class

Revision ID: d653e9815e5f
Revises: a914f98db902
Create Date: 2020-12-18 10:14:21.492189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd653e9815e5f'
down_revision = 'a914f98db902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('apg', sa.Float(), nullable=True))
    op.add_column('player', sa.Column('bpg', sa.Float(), nullable=True))
    op.add_column('player', sa.Column('fta', sa.Float(), nullable=True))
    op.add_column('player', sa.Column('ftp', sa.Float(), nullable=True))
    op.add_column('player', sa.Column('mpg', sa.Float(), nullable=True))
    op.add_column('player', sa.Column('pos', sa.String(), nullable=True))
    op.add_column('player', sa.Column('ppg', sa.Float(), nullable=True))
    op.add_column('player', sa.Column('rpg', sa.Float(), nullable=True))
    op.add_column('player', sa.Column('spg', sa.Float(), nullable=True))
    op.add_column('player', sa.Column('team', sa.String(), nullable=True))
    op.add_column('player', sa.Column('thpa', sa.Float(), nullable=True))
    op.add_column('player', sa.Column('thpp', sa.Float(), nullable=True))
    op.add_column('player', sa.Column('topg', sa.Float(), nullable=True))
    op.add_column('player', sa.Column('tpa', sa.Float(), nullable=True))
    op.add_column('player', sa.Column('tpp', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'tpp')
    op.drop_column('player', 'tpa')
    op.drop_column('player', 'topg')
    op.drop_column('player', 'thpp')
    op.drop_column('player', 'thpa')
    op.drop_column('player', 'team')
    op.drop_column('player', 'spg')
    op.drop_column('player', 'rpg')
    op.drop_column('player', 'ppg')
    op.drop_column('player', 'pos')
    op.drop_column('player', 'mpg')
    op.drop_column('player', 'ftp')
    op.drop_column('player', 'fta')
    op.drop_column('player', 'bpg')
    op.drop_column('player', 'apg')
    # ### end Alembic commands ###
